[package]
name = "containerd-shim-cwasi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "~0.4"
clap = { version = "3.1.15", features = ["derive", "env"] }
containerd-shim = "~0.3"
containerd-shim-wasm = { git = "https://github.com/containerd/runwasi", branch = "main" }
log = "~0.4"
tokio = { version = "1", features = [ "full" ] }
tokio-util = { version = "0.6.10", features = [ "codec" ]}
#wasmtime = "0.39"
toml = "0.5"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing = { version = "0.1", features = ["log"] }
openssl = { version = "0.10", features = ["vendored"] }
libc = "0.2"
wasmedge-sdk = { version = "0.7.1", features = ["async"] }

[dependencies.openssl-sys]
features = ["vendored"]

[dependencies.isahc]
version = "0.9.14"

[dependencies.curl]
features = ["zlib-ng-compat"]
